global:
  evaluation_interval: 3s
  external_labels: {monitor: sonata-monitor}
  scrape_interval: 3s
rule_files: [/opt/Monitoring/prometheus/rules/alert.rules]
scrape_configs:
- job_name: sonata
  scrape_interval: 5s
  scrape_timeout: 10s
  target_groups:
  - labels: {group: development}
    targets: ['pushgateway:9091']
  - labels: {pop: athens1}
    targets: ['10.100.32.200:9091']
  - labels: {pop: athens2}
    targets: ['10.100.33.2:9091']
  - labels: {pop: athens3}
    targets: ['10.100.16.20:9091']
  
